from pathlib import Path

WIDTH = 1400
HEIGHT = 900
DEFAULT_MODEL = "BUNNY"
DEFAULT_SEED = 7

NOISE_LEVEL_MIN = 0.02
NOISE_LEVEL_MAX = 0.20
DEFAULT_NOISE_LEVEL = 0.05

SMOOTHING_STRENGTH_MAX = 0.80
DEFAULT_SMOOTHING_STRENGTH = 0.30
ITERATIONS_PER_PRESS = 10

ROOT = Path(__file__).resolve().parent
RESOURCE_DIR = ROOT / "resources"
OUTPUT_DIR = ROOT / "outputs"
